### ISSUE TITLE
[Server] Authentication

### ISSUE THREAD

**Issue by BillZito** [hr-memories/greenfield#17]
[X] Decide on web tokens, facebook authentication, or something else
[X] Store JWT on client side and return with every request
[X] On server side, check for JWT before processing each request
[X] Don't allow access to a page if there is no webtoken in asynch storage
[X] Store the jwt secret and database credentials in config file rather than hard-coded

Resources: 
https://auth0.com/blog/adding-authentication-to-react-native-using-jwt/
https://dzone.com/articles/adding-authentication-to-your-react-native-app-usi-1
https://github.com/adamjmcgrath/react-native-simple-auth
https://github.com/ryanmcdermott/react-native-login
https://github.com/lussatech/react-native-base-authentication

**Comment by ghost** [comment]
Decided on JWT
