### ISSUE TITLE
[Client] Memory details

### ISSUE THREAD

**Issue by ghost** [hr-memories/greenfield#4]
Mandatory user stories:
- [X] As a user, I should see the photo I just chose to upload
- [X] As a user, I should see indicators for what is happening (uploading and/or analyzing)
- [X] As a user, I should see the outcome of the upload
- [X] As a user, I should have a way to navigate to the home-screen
- [x] As a user, I should have a way to navigate to the memory list
- [x] As a user, I should be able to select which tags are relevant to me from the analysis

Other things:
Design mocks here: https://invis.io/BN93WOO9R#/200493362_Mobile_Portrait

Open questions:

**Comment by ghost** [comment]
@kbchun and @kkinaman, how is the memory details page coming along? Have we integrated with POST /api/memories/id/123?

**Comment by kbchun** [comment]
Not quite. I'm working on it right now and will let you know when things are working correctly

**Comment by kkinaman** [comment]
This is complete now, right?

**Comment by kbchun** [comment]
correct
