### ISSUE TITLE
[Server] Routes

### ISSUE THREAD

**Issue by ghost** [hr-memories/greenfield#6]
Mandatory user stories:
[ ] As a frontend dev, I expect an /api/login endpoint
[ ] As a frontend dev, I expect an /api/signup endpoint
[ ] As a frontend dev, I expect an /api/upload endpoint
[ ] As a frontend dev, I expect an /api/memories endpoint
[ ] As a frontend dev, I expect an /api/memory/id/ endpoint

Other notes:

Open questions:

**Comment by kkinaman** [comment]
Complete. See /server/config/routes.js

[X] As a frontend dev, I expect an /api/users/login endpoint
[X] As a frontend dev, I expect an /api/users/signup endpoint
[X] As a frontend dev, I expect an /api/memories/upload endpoint
[X] As a frontend dev, I expect an /api/memories/all endpoint
[X] As a frontend dev, I expect an /api/memories/id endpoint
