### ISSUE TITLE
[Server] /api/users/signup

### ISSUE THREAD

**Issue by ghost** [hr-memories/greenfield#8]
Mandatory stories:
[X] Calling /api/signup with a POST request should create a new user
[X] If the supplied username already exists, return a 401 error
[X] Successfully creating the user should return a 201

Other things:

Open questions:
- How should authentication be done using React Native?

**Comment by kkinaman** [comment]
[X] Calling /api/signup with a POST request should create a new user
[X] Successfully creating the user should return a 201
